name: Artifact Demo 

on: push 

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      -name: Create File 
       run: echo "Hello Artifact" > file.txt
      
      -name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: my-file
         path: file.txt
  use-file:
    runs-on: ubuntu-latest
    needs: create-file

    steps:
      - name: Download Artifact 
        uses: actions/download-artifact@v4
        with:
          name: my-file

      - name: Read File 
        run: cat file.txt
